--- #YAML:1.0
name:               Ticketmaster
version:            1.02
abstract:           Calculate the change in coins
author:
    - Pan Yu <xiaocong[at]vip.163.com>
license:            Perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
